### ISSUE TITLE
change settings file format to YAML

### ISSUE THREAD

**Issue by oleksandrzelentsov** [oleksandrzelentsov/snap-sink#8]
change settings file format to YAML or just add an option to use YAML

what was this:

```
[section1]
local=file1
remote=file2
host=example.com
user=alex

[section2]
local=file3
remote=file4
host=example.org
user=victor
```

becomes this:

```
- section1:
  local: file1
  remote: file2
  host: example.com
  user: alex

- section2:
  local: file3
  remote: file4
  host: example.org
  user: victor
```

For YAML use PyYAML.
Question is open, if we need this.
